@startuml State Machine in Siever

[*] --> InitComponents
InitComponents: AddTimer: Connect to Radiostation

InitComponents --> Consensus : trigger::complete_init_components

state Timer
Timer: * Connect to Radiostation
Timer: * heartbeat to peers
Timer: * leader complain

state Consensus {
    [*] --> BlockHeightSync : trigger::block_height_sync

    state BlockHeightSync {
        [*] --> EvaluateNetwork : trigger::evaluate_network

        EvaluateNetwork: Check Leader
        EvaluateNetwork --> BlockSync : (if leader != self)\ntrigger::block_sync
        EvaluateNetwork --> SubscribeNetwork : (if leader == self)\ntrigger::subscribe_network

        BlockSync: StopTimer: leader complain
        BlockSync: Check Highest Block in Network
        BlockSync --> SubscribeNetwork : Succeeded\ntrigger::subscribe_network

        SubscribeNetwork: Connect Network (Subscribe to Radiostation, Join a quorum if not yet)
        SubscribeNetwork -up-> EvaluateNetwork
        SubscribeNetwork -right-> [*]
    }
    BlockHeightSync --> BlockGenerate: (if leader == self)\ntrigger::complete_sync
    BlockHeightSync -> Vote: (if leader != self)\ntrigger::complete_sync

    Vote: before {
    Vote: \tStopTimer: heartbeat to peers
    Vote: \tAddTimer: leader complain
    Vote: }
    Vote: 
    Vote: trigger {
    Vote: \tvote: do vote\n\t(Recv AnnounceUnConfirmedBlock (block.height == mine + 1))
    Vote: }
    Vote -left-> BlockHeightSync : Recv AnnounceUnConfirmedBlock\n(block.height >= mine + 2)
    Vote -> BlockGenerate : Recv AnnounceUnConfirmedBlock\n(if next leader == self)
    Vote -> LeaderComplain : !Recv heartbeat from leader by Timer (leader complain) \nSend LeaderComplain

    BlockGenerate: before {
    BlockGenerate: \tStopTimer: leader complain
    BlockGenerate: \tAddTimer: heartbeat to peers
    BlockGenerate: }
    BlockGenerate: 
    BlockGenerate: trigger {
    BlockGenerate: \tadd_tx: make block\n\t(Recv AddTx)
    BlockGenerate: }
    BlockGenerate -> Vote : Send AnnounceConfirmedBlock\n(made block count == max)

    state LeaderComplain
    note right of LeaderComplain
      keep leader complain Timer
      until new leader elected
    end note
    LeaderComplain -> Vote : Recv AnnounceNewLeader\n(if next leader != self)
    LeaderComplain --> BlockGenerate : Send AnnounceNewLeader\n(if next leader == self)
}

Consensus --> GracefulShutdown

GracefulShutdown: StopTimer: ALL
GracefulShutdown --> [*]

@enduml