repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
   - id: flake8
     additional_dependencies: [
      "flake8-builtins",
      "flake8-docstrings",
      "flake8-import-order",
      "flake8-logging-format",
     ]
     exclude: "^proto.*|^setup.*"
