import enum


class ChannelConfigKey(enum.Enum):
    BLOCK_VERSIONS = "block_versions"
    HASH_VERSIONS = "hash_versions"
    LOAD_CERT = "load_cert"
    CONSENSUS_CERT_USE = "consensus_cert_use"
    TX_CERT_USE = "tx_cert_use"
    KEY_LOAD_TYPE = "key_load_type"
    GENESIS_DATA_PATH = "genesis_data_path"
    RADIOSTATIONS = "radiostations"


class PeerConfigKey(enum.Enum):
    LOOPCHAIN_DEFAULT_CHANNEL = "LOOPCHAIN_DEFAULT_CHANNEL"
    CHANNEL_OPTION = "CHANNEL_OPTION"
    PRIVATE_PATH = "PRIVATE_PATH"
    PRIVATE_PASSWORD = "PRIVATE_PASSWORD"
    RUN_ICON_IN_LAUNCHER = "RUN_ICON_IN_LAUNCHER"
    ALLOW_MAKE_EMPTY_BLOCK = "ALLOW_MAKE_EMPTY_BLOCK"
    PORT_PEER = "PORT_PEER"
    PEER_ORDER = "PEER_ORDER"
    PEER_ID = "PEER_ID"
    LOOPCHAIN_DEVELOP_LOG_LEVEL = "LOOPCHAIN_DEVELOP_LOG_LEVEL"
    DEFAULT_STORAGE_PATH = "DEFAULT_STORAGE_PATH"
    CHANNEL_MANAGE_DATA_PATH = "CHANNEL_MANAGE_DATA_PATH"
